# Base image with all dependencies installed to build Tuwunel
name: Building base image
on:
    push:
        branches:
            - cicd/builder-image

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        env:
            RUST_VERSION: 1.86
            IMAGE_NAME: tuwenel-builder
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Create Dockerfile content
              id: dockerfile
              run: |
                  cat > Dockerfile << EOF
                  FROM rust:${{ env.RUST_VERSION }} AS lib
                  ENV packages="\
                  bzip2 \
                  ca-certificates \
                  clang \
                  cmake \
                  curl \
                  git \
                  libc6-dev \
                  make \
                  pkg-config \
                  pkgconf \
                  xz-utils \
                  libjemalloc-dev \
                  liburing-dev \
                  libzstd-dev \
                  liburing2 \
                  libzstd1 \
                  libjemalloc2 \
                  "
                  RUN apt-get update && apt-get -y install --no-install-recommends \$packages
                  EOF

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.RUST_VERSION }}
